version: '3.8'

services:
  app:
    image: la-flamita-admin
    container_name: flamita-container
    ports:
      - "${PORT:-8000}:${PORT:-8000}"
    restart: unless-stopped
    env_file: 
      - .env
    volumes:
      - flamita-admin-storage:/usr/src/app/public/storage
    networks:
      - flamita-network

networks:
  flamita-network:
    driver: bridge

volumes:
  flamita-admin-storage:
    driver: local